``CustomDOE.compute_doe`` no longer raises an error and works correctly.
